const DocForm = [
	'owner',
	'name',
	'type',
	'facility',
	'description',
	'documentNumber',
	'gst',
	'totalValue',
	'subjectAddress',
	'currentYear',
	'currentYear+1',
	'currentYear+2',
	'serviceType',
	'supplier',
	'issuer',
	'insuranceType',
	'applicablePeriodStartDate',
	'applicablePeriodEndDate',
	'tenantExecutedDate',
	'lessorExecutedDate',
	'tenant',
	'landlord',
	'commencingRent',
	'commencementDate',
	'expiryDate',
	'issueDate',
	'clientExecutedDate',
	'supplierExecutedDate',
	'annualReview',
	'reviewMethod',
	'reviewAmount',
	'optionExerciseFromDate',
	'optionExerciseToDate',
	'area',
	'private',
	'visibleTo',
	'attachments',

]

export default DocForm;
