export default DocTypes = [
    "Audit",
    "Bank Guarantee",
    "Budget",
    "Contract",
    "Emergency Management",
    "House Rules",
    "Induction",
    "Inspection",
    "Insurance",
    "Invoice",
    "Lease",
    "MSDS",
    "Plan",
    "Procedure",
    "Quote",
    "Register",
    "Registration",
    "Service Report",
    "SWMS",
];