export default CreateRequestForm = [
	/*'team',*/
	'type',
	/* 'occupancy', */
	'facility',
	'location',
	'incidentVictim',
	'reporter',
	'name',
	'reporterContact',
	'level',
	'area',
	'identifier',
	'bookingRules',
	'bookingPeriod',
	'service',
	'subservice',
	'supplier',
	'supplierContact',
	'assignee',
	'priority',
	'dueDate',
	'frequency',
	'number',
	'period',
	'endDate',
	'incidenceDate',
	'duration',
	'costThreshold',
	//'requireServiceReport',
	//'requireInvoice',

	'memberName',
	'numberOfPersons',
	'description',
	'incidentFurtherComments',
	'attachments',
	'footer'

];
